// Auth Types
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// Ticket Types
export const FETCH_TICKETS_REQUEST = "FETCH_TICKETS_REQUEST";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_FAILURE = "FETCH_TICKETS_FAILURE";
export const UPDATE_TICKET_STATUS = "UPDATE_TICKET_STATUS";
export const DELETE_TICKET = "DELETE_TICKET";
export const SET_TICKET_FILTER = "SET_TICKET_FILTER";
export const SET_TICKET_SEARCH = "SET_TICKET_SEARCH";
