// Auth Types
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGOUT = "LOGOUT";

// Ticket Types
export const GET_TICKETS = "GET_TICKETS";
export const GET_TICKET = "GET_TICKET";
export const CREATE_TICKET = "CREATE_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const UPDATE_TICKET_STATUS = "UPDATE_TICKET_STATUS";
export const DELETE_TICKET = "DELETE_TICKET";
export const TICKET_ERROR = "TICKET_ERROR";
export const SET_TICKET_FILTER = "SET_TICKET_FILTER";
export const SET_TICKET_SEARCH = "SET_TICKET_SEARCH";

// Loading Types
export const FETCH_TICKETS_REQUEST = "FETCH_TICKETS_REQUEST";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_FAILURE = "FETCH_TICKETS_FAILURE";
